apiVersion: v1
kind: Pod
metadata:
  name: logapp-loop
  labels:
    app: logapp-loop

spec:
  restartPolicy: OnFailure
  containers:
  - name: app
    imagePullPolicy: Always
    image: ghcr.io/retaildevcrews/logapp:latest
    args:
    - --loop
    - --sleep
    - "1000"
